package pcsc

func errorString(code uint32) string {
    str := "Unknown error"
    switch code {
        case SCARD_F_INTERNAL_ERROR:
            str ="SCARD_F_INTERNAL_ERROR"
        case SCARD_E_CANCELLED:
            str ="SCARD_E_CANCELLED"
        case SCARD_E_INVALID_HANDLE:
            str ="SCARD_E_INVALID_HANDLE"
        case SCARD_E_INVALID_PARAMETER:
            str ="SCARD_E_INVALID_PARAMETER"
        case SCARD_E_INVALID_TARGET:
            str ="SCARD_E_INVALID_TARGET"
        case SCARD_E_NO_MEMORY:
            str ="SCARD_E_NO_MEMORY"
        case SCARD_F_WAITED_TOO_LONG:
            str ="SCARD_F_WAITED_TOO_LONG"
        case SCARD_E_INSUFFICIENT_BUFFER:
            str ="SCARD_E_INSUFFICIENT_BUFFER"
        case SCARD_E_UNKNOWN_READER:
            str ="SCARD_E_UNKNOWN_READER"
        case SCARD_E_TIMEOUT:
            str ="SCARD_E_TIMEOUT"
        case SCARD_E_SHARING_VIOLATION:
            str ="SCARD_E_SHARING_VIOLATION"
        case SCARD_E_NO_SMARTCARD:
            str ="SCARD_E_NO_SMARTCARD"
        case SCARD_E_UNKNOWN_CARD:
            str ="SCARD_E_UNKNOWN_CARD"
        case SCARD_E_CANT_DISPOSE:
            str ="SCARD_E_CANT_DISPOSE"
        case SCARD_E_PROTO_MISMATCH:
            str ="SCARD_E_PROTO_MISMATCH"
        case SCARD_E_NOT_READY:
            str ="SCARD_E_NOT_READY"
        case SCARD_E_INVALID_VALUE:
            str ="SCARD_E_INVALID_VALUE"
        case SCARD_E_SYSTEM_CANCELLED:
            str ="SCARD_E_SYSTEM_CANCELLED"
        case SCARD_F_COMM_ERROR:
            str ="SCARD_F_COMM_ERROR"
        case SCARD_F_UNKNOWN_ERROR:
            str ="SCARD_F_UNKNOWN_ERROR"
        case SCARD_E_INVALID_ATR:
            str ="SCARD_E_INVALID_ATR"
        case SCARD_E_NOT_TRANSACTED:
            str ="SCARD_E_NOT_TRANSACTED"
        case SCARD_E_READER_UNAVAILABLE:
            str ="SCARD_E_READER_UNAVAILABLE"
        case SCARD_P_SHUTDOWN:
            str ="SCARD_P_SHUTDOWN"
        case SCARD_E_PCI_TOO_SMALL:
            str ="SCARD_E_PCI_TOO_SMALL"
        case SCARD_E_READER_UNSUPPORTED:
            str ="SCARD_E_READER_UNSUPPORTED"
        case SCARD_E_DUPLICATE_READER:
            str ="SCARD_E_DUPLICATE_READER"
        case SCARD_E_CARD_UNSUPPORTED:
            str ="SCARD_E_CARD_UNSUPPORTED"
        case SCARD_E_NO_SERVICE:
            str ="SCARD_E_NO_SERVICE"
        case SCARD_E_SERVICE_STOPPED:
            str ="SCARD_E_SERVICE_STOPPED"
        case SCARD_E_UNEXPECTED:
            str ="SCARD_E_UNEXPECTED"
        case SCARD_E_ICC_INSTALLATION:
            str ="SCARD_E_ICC_INSTALLATION"
        case SCARD_E_ICC_CREATEORDER:
            str ="SCARD_E_ICC_CREATEORDER"
        case SCARD_E_UNSUPPORTED_FEATURE:
            str ="SCARD_E_UNSUPPORTED_FEATURE"
        case SCARD_E_DIR_NOT_FOUND:
            str ="SCARD_E_DIR_NOT_FOUND"
        case SCARD_E_FILE_NOT_FOUND:
            str ="SCARD_E_FILE_NOT_FOUND"
        case SCARD_E_NO_DIR:
            str ="SCARD_E_NO_DIR"
        case SCARD_E_NO_FILE:
            str ="SCARD_E_NO_FILE"
        case SCARD_E_NO_ACCESS:
            str ="SCARD_E_NO_ACCESS"
        case SCARD_E_WRITE_TOO_MANY:
            str ="SCARD_E_WRITE_TOO_MANY"
        case SCARD_E_BAD_SEEK:
            str ="SCARD_E_BAD_SEEK"
        case SCARD_E_INVALID_CHV:
            str ="SCARD_E_INVALID_CHV"
        case SCARD_E_UNKNOWN_RES_MNG:
            str ="SCARD_E_UNKNOWN_RES_MNG"
        case SCARD_E_NO_SUCH_CERTIFICATE:
            str ="SCARD_E_NO_SUCH_CERTIFICATE"
        case SCARD_E_CERTIFICATE_UNAVAILABLE:
            str ="SCARD_E_CERTIFICATE_UNAVAILABLE"
        case SCARD_E_NO_READERS_AVAILABLE:
            str ="SCARD_E_NO_READERS_AVAILABLE"
        case SCARD_E_COMM_DATA_LOST:
            str ="SCARD_E_COMM_DATA_LOST"
        case SCARD_E_NO_KEY_CONTAINER:
            str ="SCARD_E_NO_KEY_CONTAINER"
        case SCARD_E_SERVER_TOO_BUSY:
            str ="SCARD_E_SERVER_TOO_BUSY"
        case SCARD_W_UNSUPPORTED_CARD:
            str ="SCARD_W_UNSUPPORTED_CARD"
        case SCARD_W_UNRESPONSIVE_CARD:
            str ="SCARD_W_UNRESPONSIVE_CARD"
        case SCARD_W_UNPOWERED_CARD:
            str ="SCARD_W_UNPOWERED_CARD"
        case SCARD_W_RESET_CARD:
            str ="SCARD_W_RESET_CARD"
        case SCARD_W_REMOVED_CARD:
            str ="SCARD_W_REMOVED_CARD"
        case SCARD_W_SECURITY_VIOLATION:
            str ="SCARD_W_SECURITY_VIOLATION"
        case SCARD_W_WRONG_CHV:
            str ="SCARD_W_WRONG_CHV"
        case SCARD_W_CHV_BLOCKED:
            str ="SCARD_W_CHV_BLOCKED"
        case SCARD_W_EOF:
            str ="SCARD_W_EOF"
        case SCARD_W_CANCELLED_BY_USER:
            str ="SCARD_W_CANCELLED_BY_USER"
        case SCARD_W_CARD_NOT_AUTHENTICATED :
            str ="SCARD_W_CARD_NOT_AUTHENTICATED "
    }
    return str
}
